using Azurite;
using UnityEngine;
using UnityEngine.Rendering;
using Studio.Scripts;
int passed = 0;
void Check(bool value, string name) { if (!value) throw new Exception(name); passed++; Console.WriteLine("PASS " + name); }
RenderTexture Target() { var target = new RenderTexture(new() { width = 1920, height = 1080, volumeDepth = 1, dimension = TextureDimension.Tex2D }); target.name = "Preview"; target.Create(); return target; }
var target = Target(); var camera = new Camera { targetTexture = target };
var consumer = new UITexture { mainTexture = target };
var panel = new UIPanel(); int foreignCalls = 0;
var foreign = new UIPanel.OnGeometryUpdated(() => foreignCalls++); panel.onGeometryUpdated = foreign;
var preview = new Test { background = new UITexture { anchorCamera = camera }, frontPanel = panel };
var inspector = new ScriptNodeInspector { preview = preview }; inspector.Textures.Add(consumer); ScriptNodeInspector.instance = inspector;
using var cadence = new PreviewCameraCadence();
for (int i = 0; i < 640; i++) cadence.Update(i / 320.0, true, 60, cacheStatic: true);
Check(cadence.ScheduledFrames == 2 && cadence.SkippedFrames == 638, "static cached preview schedules only safety refreshes while the UI can draw every frame");
Check(!camera.enabled && ReferenceEquals(camera.targetTexture, target), "static caching retains the existing texture and suppresses only its camera");
panel.onGeometryUpdated!.Invoke(); cadence.Update(2.01, true, 60, cacheStatic: true);
Check(camera.enabled && foreignCalls == 1, "native preview geometry wakes the camera and preserves foreign callbacks");
cadence.Update(2.02, true, 60, cacheStatic: true); Check(!camera.enabled, "unchanged content returns to cache after its redraw");
panel.onClipMove!.Invoke(panel); cadence.Update(2.03, true, 60, cacheStatic: true);
Check(camera.enabled, "preview clipping changes invalidate cached content");
cadence.Update(2.04, true, 60, cacheStatic: true);
camera.transform.localToWorldMatrix = new(2); cadence.Update(2.05, true, 60, cacheStatic: true);
Check(camera.enabled, "preview camera transform changes force a fresh frame");
OnDemandRendering.willCurrentFrameRender = false; cadence.Invalidate(); cadence.Update(2.06, true, 60, cacheStatic: true);
Check(!camera.enabled, "whole-player skipped frames do not consume a dirty preview deadline");
OnDemandRendering.willCurrentFrameRender = true; cadence.Update(2.07, true, 60, cacheStatic: true);
Check(camera.enabled, "the next actual player draw services pending content invalidation");
cadence.Update(2.08, false, 60, cacheStatic: true);
Check(camera.enabled && ReferenceEquals(panel.onGeometryUpdated, foreign) && panel.onClipMove == null, "export or configuration disable restores the camera and removes only owned callbacks");
cadence.Update(2.09, true, 60, cacheStatic: true); panel.onGeometryUpdated!.Invoke(); cadence.Update(2.10, true, 60, cacheStatic: true);
Check(camera.enabled && foreignCalls == 2, "resuming before the next discovery deadline immediately rebinds content callbacks");
cadence.Update(2.11, true, 60, cacheStatic: true);
preview.frontPanel = null; cadence.Update(2.12, true, 60, cacheStatic: true);
Check(camera.enabled, "missing content observation releases caching instead of freezing the preview");
preview.frontPanel = panel; cadence.Update(3.2, true, 60, cacheStatic: true);
Check(camera.enabled, "confirmed content can resume after re-discovery");
cadence.Update(3.3, true, 60, cacheStatic: true, safetyFps: double.NaN);
Check(camera.enabled && ReferenceEquals(panel.onGeometryUpdated, foreign), "invalid safety refresh configuration restores normal rendering");
cadence.Dispose(); cadence.Update(4, true, 60, cacheStatic: true);
Check(camera.enabled && ReferenceEquals(panel.onGeometryUpdated, foreign), "disposal retains no native content observer and cannot reacquire the camera");
Console.WriteLine($"RESULT {passed}/{passed}; source-linked preview camera and content-cache lifecycle checks; not GPU measurements.");
